version: '3'
services:
  app:
    container_name: sigalei-stack-app
    image: sigalei/stack-app
    build:
      context: ./.docker
      dockerfile: node.dockerfile
    volumes:
      - ./:/home/node/app
    ports:
      - ${DOCKER_NODE_PORT}:5000
    depends_on:
      - postgresql
    networks: 
      - sigalei-stack-network
    environment:
      - NODE_ENV=${DOCKER_NODE_ENV}

  postgresql:
    image: postgres:9.6
    container_name: sigalei-stack-db
    restart: always
    volumes:
      - ./.docker/data/postgresql:/var/lib/postgresql/data
    ports:
      - ${DOCKER_PG_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks: 
      - sigalei-stack-network
  
  pgadmin:
    image: thajeztah/pgadmin4
    container_name: sigalei-stack-pgadmin
    ports:
     - ${DOCKER_PGADMIN_PORT}:5050
    volumes:
     - ./.docker/data/pgadmin:/pgadmin:rw
    networks:
      - sigalei-stack-network
    depends_on:
      - postgresql

networks: 
  sigalei-stack-network:
    driver: bridge